name: Azure Smoke Test

on:
  push:
    branches:
      - main

jobs:
  test-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show Subscription
        run: |
          az account show --query "{subscriptionId:id, tenantId:tenantId}" -o table
